language: java
jdk:
- oraclejdk8
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
 - secure: "ocO1M09ai1GA2J+s5AklaVq1deXVmtZQDUPqLMD4EFVQ0MQwM21de0G+oA67R8yPzhe0c5XlOdAHlZay2BeG8XobWiqxUpQbI/kSUGFeuaLYJDugTPbOtEUh5n+03mG0F5XFA0D1OVYDhbm1pZgqkGJdsCiz5bEofJpfVz7AsIDWGj8f0iK7mQjfJRP7hUT7a9DjqkZmxJSrrdJjpgdTKP5rkDt2GfzH1Jkyk1QV0+oyz5jx6+MiwrfS46ECZaw/0QLddhBL32GQNtABPExHflpwyyB5TB1ocPZmXEECH0beDuAuz7NJrfMDRaElQLrSkgfIMxFAQgJqjUmiTPn18mgH3oyvSBVPBB05jlOb3ihy6uN9kc9SydDJ+sR0O2ObuVfDb4WMsNxrsWYAl1Kefx1ZLIm8u4KXPoTflHnP+Gme9eCBiLW0dtysJT4EYkjRtKWdNuG58nR06Yb9lyMckgRtb8tSOjKoB84ol7b7yN8/V589PPe+a5XbidfnF/vTobj0vKXMmF85QLm4M8SeED38gsNovSe3J6LOIKU/CKaOmSxOlRPTx18xI++nDh0x7lbyntTVQ6Qz/6jv82K/3/TXUnuRKn8MVzYVgH+wLzJIvKcp4o6guRNSnQklP3en5/Cta8P0EFFXGyteJcXIhXmyYbdtYlYTSFAMTDeqjPE="
addons:
  coverity_scan:
    project:
      name: "POPBL-6/middleware"
      description: "Build submitted via Travis CI"
    notification_email: 
        secure: "L4DeYWQb03VuJqhIiPCBIbQdAjMjHeMOkjuKVnxJ5qHpNlTx4Mun/uQAYwm5MgUhsU6oa2QCdlGlAQHzkBUnuVGV+zdbD78UmQ6qnHFyg85sc3/23uvg+4Alqn3BMJ211PU6fHlCSf/LTryLFYTXFQf5k6K/c03k3NylY46rsRviGSsINXFo6ue5JgW/12OK2rXkp0VjrSO1wyyDy44VOiEnk/GOxHNx1QWDI6lW5MeXyQklZzB2C9HD7mG0FB5lCGE3z2EPvRqZ64I27xdsZkWjPNLEsZTpMW2Lfisa6drDTwLGj+6oyESTIpebMREVjCn5ep8afohahI2ZmMX3akyiVd0YXHKH5/cnr/NMwbcuQf8p2Yw6ZdCxWjFdqRT20MmuhN77BCZRK4Do5XNRHfo/Yz6JcOxsxqW1o6SOiBB5bEvbXvU6D4HWsuszCXyg2GVBWRNrUFoUlfKO3HPU1FXiyFv5OD/92z+XXL3CbJ02ub142WzEJVTeDTNkn50w++9GI3H7JlbCDHTdXoe1vT6DyAhxyvjBnApHeR0aZwfUDsJllGN5eMAJUGz3a+yaGeFDXig01EvO2FB3qtNfXUWEuMs+OvdJeXx7WQdTvWL/7EX36oaTwkk8Y+QcUxGpvsWkYPrGj+YUKq4jEBdvo8kTv257Pg8TvHRZw6/0jyQ="
    build_command_prepend: "gradle clean"
    build_command:   "gradle -x test build"
    branch_pattern: coverity_scan
